version: '3'
services:

  web:
  
    build: .
    image: myapp-python
    container_name: myapp-python
    ports:
      - "5000:5000"
    links: 
      - mongo
  mongo:

    image: mongo
    container_name: mongo
    ports:
      - '27017-27017'
